export const tasks = [
    {
      title: '完成项目报告',
      details: '撰写并提交项目的最终报告。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-10T14:00:00Z',
    },
    {
      title: '回复客户邮件',
      details: '回复客户关于项目进度的询问邮件。',
      isCompleted: true,
      completionDate: '2023-10-05T14:30:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T14:30:00Z',
    },
    {
      title: '准备会议材料',
      details: '为下周的项目会议准备所需材料。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: true,
      expectedCompletionDate: '2023-10-08T10:00:00Z',
    },
    {
      title: '更新软件版本',
      details: '将应用软件更新到最新版本。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-12T09:00:00Z',
    },
    {
      title: '健身训练',
      details: '进行一小时的健身锻炼。',
      isCompleted: true,
      completionDate: '2023-10-05T17:00:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T17:00:00Z',
    },
    {
      title: '阅读新书',
      details: '阅读《深入浅出Vue.js》一书。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-15T20:00:00Z',
    },
    {
      title: '整理办公桌',
      details: '整理和清理办公桌，保持整洁。',
      isCompleted: true,
      completionDate: '2023-10-05T12:00:00Z',
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T12:00:00Z',
    },
    {
      title: '参加在线课程',
      details: '报名并参加有关前端开发的在线课程。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-10T08:00:00Z',
    },
    {
      title: '计划周末出行',
      details: '为周末的出行制定具体计划。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-06T18:00:00Z',
    },
    {
      title: '提交预算申请',
      details: '准备并提交下一季度的预算申请。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-13T10:00:00Z',
    },
    {
      title: '编写代码',
      details: '编写项目代码。',
      isCompleted: true,
      completionDate: '2023-10-01T15:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-01T15:00:00Z',
    },
    {
      title: '整理文件',
      details: '整理个人文件。',
      isCompleted: true,
      completionDate: '2023-10-01T10:00:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-01T10:00:00Z',
    },
    {
      title: '学习新技能',
      details: '学习一项新技能。',
      isCompleted: true,
      completionDate: '2023-10-02T12:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-02T12:00:00Z',
    },
    {
      title: '购物清单',
      details: '制定购物清单。',
      isCompleted: true,
      completionDate: '2023-10-02T14:00:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-02T14:00:00Z',
    },
    {
      title: '整理照片',
      details: '整理个人照片。',
      isCompleted: true,
      completionDate: '2023-10-03T11:00:00Z',
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-10-03T11:00:00Z',
    },
    {
      title: '编写测试用例',
      details: '编写项目测试用例。',
      isCompleted: true,
      completionDate: '2023-10-03T13:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-03T13:00:00Z',
    },
    {
      title: '学习JavaScript',
      details: '深入学习JavaScript。',
      isCompleted: true,
      completionDate: '2023-10-04T16:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-04T16:00:00Z',
    },
    {
      title: '学习CSS',
      details: '学习CSS以提升网站设计技能。',
      isCompleted: true,
      completionDate: '2023-10-04T18:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-04T18:00:00Z',
    },
    {
      title: '优化网站',
      details: '优化公司网站以提高用户体验。',
      isCompleted: true,
      completionDate: '2023-10-05T10:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T10:00:00Z',
    },
    {
      title: '计划下个月预算',
      details: '制定下个月的个人预算。',
      isCompleted: true,
      completionDate: '2023-10-05T12:00:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T12:00:00Z',
    },
    {
      title: '学习React',
      details: '学习React以增强前端开发能力。',
      isCompleted: true,
      completionDate: '2023-10-05T15:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T15:00:00Z',
    },
    {
      title: '学习ES6',
      details: '学习ES6以提高代码质量。',
      isCompleted: true,
      completionDate: '2023-10-06T10:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-06T10:00:00Z',
    },
    {
      title: '提交项目进度',
      details: '向主管提交项目进度报告。',
      isCompleted: true,
      completionDate: '2023-10-06T12:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-06T12:00:00Z',
    },
    {
      title: '学习Vue',
      details: '学习Vue框架以用于新项目。',
      isCompleted: true,
      completionDate: '2023-10-07T14:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-07T14:00:00Z',
    },
    {
      title: '学习HTML',
      details: '学习HTML以创建网站结构。',
      isCompleted: true,
      completionDate: '2023-10-07T16:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-07T16:00:00Z',
    },
    {
      title: '完成项目文档',
      details: '完成项目的详细文档。',
      isCompleted: true,
      completionDate: '2023-10-08T11:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-08T11:00:00Z',
    },
    {
      title: '学习TypeScript',
      details: '学习TypeScript以提高项目稳定性。',
      isCompleted: true,
      completionDate: '2023-10-08T13:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-08T13:00:00Z',
    },
    {
      title: '学习Node.js',
      details: '学习Node.js以增强后端开发技能。',
      isCompleted: true,
      completionDate: '2023-10-09T12:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-09T12:00:00Z',
    },
    {
      title: '设计公司LOGO',
      details: '设计公司新的LOGO。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-09T14:00:00Z',
    },
    {
      title: '学习Angular',
      details: '学习Angular以用于新项目。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-10T09:00:00Z',
    },
    {
      title: '学习SQL',
      details: '学习SQL以提高数据库操作能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-10T11:00:00Z',
    },
    {
      title: '准备项目策划',
      details: '准备下个项目的策划方案。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-11T09:00:00Z',
    },
    {
      title: '学习Webpack',
      details: '学习Webpack以优化前端构建。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-11T11:00:00Z',
    },
    {
      title: '学习Docker',
      details: '学习Docker以用于容器化部署。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-11T13:00:00Z',
    },
    {
      title: '准备演讲',
      details: '准备下周的演讲内容。',
      isCompleted: false,
      completionDate: null,
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-10-12T09:00:00Z',
    },
    {
      title: '创建个人网站',
      details: '创建一个个人网站以展示自己的作品。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-12T11:00:00Z',
    },
    {
      title: '学习Vue 3',
      details: '学习Vue 3以提升前端技能。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-13T09:00:00Z',
    },
    {
      title: '学习Python',
      details: '学习Python以提高后端开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-13T11:00:00Z',
    },
    {
      title: '学习Express.js',
      details: '学习Express.js以创建后端服务。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-14T09:00:00Z',
    },
    {
      title: '学习Sass',
      details: '学习Sass以提高样式开发效率。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-14T11:00:00Z',
    },
    {
      title: '学习Git',
      details: '学习Git以提高代码版本控制能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-15T09:00:00Z',
    },
    {
      title: '学习RESTful API',
      details: '学习RESTful API以提高接口设计能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-15T11:00:00Z',
    },
    {
      title: '学习GraphQL',
      details: '学习GraphQL以实现更灵活的数据查询。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-16T09:00:00Z',
    },
    {
      title: '学习Flutter',
      details: '学习Flutter以开发跨平台应用。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-16T11:00:00Z',
    },
    {
      title: '设计产品原型',
      details: '设计产品的初步原型。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-17T09:00:00Z',
    },
    {
      title: '学习Ruby',
      details: '学习Ruby以提高后端开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-17T11:00:00Z',
    },
    {
      title: '学习Swift',
      details: '学习Swift以开发iOS应用。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-18T09:00:00Z',
    },
    {
      title: '学习Kotlin',
      details: '学习Kotlin以开发Android应用。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-18T11:00:00Z',
    },
    {
      title: '学习React Native',
      details: '学习React Native以开发跨平台移动应用。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-19T09:00:00Z',
    },
    {
      title: '学习Rust',
      details: '学习Rust以提高系统编程能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-19T11:00:00Z',
    },
    {
      title: '学习Go',
      details: '学习Go以提高服务器端开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-20T09:00:00Z',
    },
    {
      title: '学习C#',
      details: '学习C#以提高Windows应用开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-20T11:00:00Z',
    },
    {
      title: '学习R',
      details: '学习R以提高数据分析能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-21T09:00:00Z',
    },
    {
      title: '学习Scala',
      details: '学习Scala以提高大型系统开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-21T11:00:00Z',
    },
    {
      title: '学习Haskell',
      details: '学习Haskell以提高函数式编程能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-22T09:00:00Z',
    },
    {
      title: '学习Django',
      details: '学习Django以提高Python Web开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-22T11:00:00Z',
    },
    {
      title: '学习Spring Boot',
      details: '学习Spring Boot以提高Java后端开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-23T09:00:00Z',
    },
    {
      title: '学习Laravel',
      details: '学习Laravel以提高PHP后端开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-23T11:00:00Z',
    },
    {
      title: '学习Spring',
      details: '学习Spring以提高Java后端开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-24T09:00:00Z',
    },
    {
      title: '学习Flask',
      details: '学习Flask以提高Python Web开发能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-24T11:00:00Z',
    },
    {
      title: '学习Vue CLI',
      details: '学习Vue CLI以简化项目开发。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-25T09:00:00Z',
    },
    {
      title: '学习Redux',
      details: '学习Redux以提高前端状态管理能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-25T11:00:00Z',
    },
    {
      title: '学习Webpack DevServer',
      details: '学习Webpack DevServer以提高开发效率。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-26T09:00:00Z',
    },
    {
      title: '学习D3.js',
      details: '学习D3.js以提高数据可视化能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-26T11:00:00Z',
    },
    {
      title: '学习TypeScript编译器',
      details: '学习TypeScript编译器的使用方法。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-27T09:00:00Z',
    },
    {
      title: '学习Vue Router',
      details: '学习Vue Router以实现单页应用的路由管理。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-27T11:00:00Z',
    },
    {
      title: '学习React Router',
      details: '学习React Router以实现单页应用的路由管理。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-28T09:00:00Z',
    },
    {
      title: '学习Spring Security',
      details: '学习Spring Security以提高应用安全性。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-28T11:00:00Z',
    },
    {
      title: '学习Laravel Eloquent',
      details: '学习Laravel Eloquent以提高数据库操作能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-29T09:00:00Z',
    },
    {
      title: '学习Flask-SQLAlchemy',
      details: '学习Flask-SQLAlchemy以提高数据库操作能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-29T11:00:00Z',
    },
    {
      title: '学习Vue Test Utils',
      details: '学习Vue Test Utils以提高测试能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-30T09:00:00Z',
    },
    {
      title: '学习React Testing Library',
      details: '学习React Testing Library以提高测试能力。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-30T11:00:00Z',
    },
  ];
