export const tasks = [
    {
      title: '完成项目报告',
      details: '撰写并提交项目的最终报告。',
      isCompleted: true,
      completionDate: '2023-10-06T14:30:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-10T14:00:00Z',
    },
    {
      title: '回复客户邮件',
      details: '回复客户关于项目进度的询问邮件。',
      isCompleted: true,
      completionDate: '2023-10-05T14:30:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T14:30:00Z',
    },
    {
      title: '准备会议材料',
      details: '为下周的项目会议准备所需材料。',
      isCompleted: true,
      completionDate: '2023-10-07T10:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-08T10:00:00Z',
    },
    {
      title: '更新软件版本',
      details: '将应用软件更新到最新版本。',
      isCompleted: true,
      completionDate: '2023-10-05T10:30:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-12T09:00:00Z',
    },
    {
      title: '健身训练',
      details: '进行一小时的健身锻炼。',
      isCompleted: true,
      completionDate: '2023-10-05T17:00:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T17:00:00Z',
    },
    {
      title: '阅读新书',
      details: '阅读《深入浅出Vue.js》一书。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-15T20:00:00Z',
    },
    {
      title: '整理办公桌',
      details: '整理和清理办公桌，保持整洁。',
      isCompleted: true,
      completionDate: '2023-10-05T12:00:00Z',
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T12:00:00Z',
    },
    {
      title: '参加在线课程',
      details: '报名并参加有关前端开发的在线课程。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-10T08:00:00Z',
    },
    {
      title: '计划周末出行',
      details: '为周末的出行制定具体计划。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-06T18:00:00Z',
    },
    {
      title: '提交预算申请',
      details: '准备并提交下一季度的预算申请。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-13T10:00:00Z',
    },
    {
      title: '完成年度预算',
      details: '撰写并提交下年度预算。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-20T09:00:00Z',
    },
    {
      title: '参加团队建设活动',
      details: '参加公司组织的团队建设活动。',
      isCompleted: true,
      completionDate: '2023-09-15T14:30:00Z',
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-09-15T14:30:00Z',
    },
    {
      title: '学习Python编程',
      details: '完成Python入门课程。',
      isCompleted: true,
      completionDate: '2023-10-01T20:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-11-01T20:00:00Z',
    },
    {
      title: '更新个人简历',
      details: '整理并更新个人简历。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-25T10:00:00Z',
    },
    {
      title: '每周运动三次',
      details: '保持每周至少三次运动。',
      isCompleted: true,
      completionDate: '2023-10-05T17:00:00Z',
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T17:00:00Z',
    },
    {
      title: '准备生日聚会',
      details: '为朋友的生日聚会做准备。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-10-30T18:00:00Z',
    },
    {
      title: '计划家庭旅行',
      details: '制定家庭旅行的计划。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-11-15T12:00:00Z',
    },
    {
      title: '学习做饭',
      details: '每周学习一种新菜谱。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-11-10T20:00:00Z',
    },
    {
      title: '公益活动',
      details: '参与当地的公益活动。',
      isCompleted: false,
      completionDate: null,
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-11-05T10:00:00Z',
    },
    {
      title: '购置办公家具',
      details: '购买新的办公桌和椅子。',
      isCompleted: true,
      completionDate: '2023-10-02T14:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-02T14:00:00Z',
    },
    {
      title: '参加职业发展研讨会',
      details: '参加行业研讨会，提升职场技能。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-28T09:00:00Z',
    },
    {
      title: '完成个人项目',
      details: '按照计划完成个人编程项目。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-10-18T18:00:00Z',
    },
    {
      title: '参加在线英语课程',
      details: '完成在线英语学习的课程。',
      isCompleted: true,
      completionDate: '2023-09-30T16:00:00Z',
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-09-30T16:00:00Z',
    },
    {
      title: '家庭清洁大扫除',
      details: '定期进行家庭大扫除。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: true,
      expectedCompletionDate: '2023-11-25T09:00:00Z',
    },
    {
      title: '制定新年计划',
      details: '为下一年度制定个人目标。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: true,
      expectedCompletionDate: '2023-12-31T15:00:00Z',
    },
    {
      title: '更新家居装饰',
      details: '购买新的家居装饰品。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-11-20T18:00:00Z',
    },
    {
      title: '写读书笔记',
      details: '阅读后撰写读书笔记。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-28T20:00:00Z',
    },
    {
      title: '拓展人脉',
      details: '参加社交活动以拓展人脉。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-11-15T10:00:00Z',
    },
    {
      title: '参加健身课程',
      details: '每周参加一次健身课程。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-11-30T17:00:00Z',
    },
    {
      title: '制定学习计划',
      details: '为下季度的学习制定具体计划。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-31T16:00:00Z',
    },
    {
      title: '整理文件夹',
      details: '整理电子邮件和文件夹，保持整洁。',
      isCompleted: true,
      completionDate: '2023-10-05T10:00:00Z',
      category: '工作',
      isDeleted: false,
      expectedCompletionDate: '2023-10-05T10:00:00Z',
    },
    {
      title: '制定饮食计划',
      details: '为自己制定健康饮食计划。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: true,
      expectedCompletionDate: '2023-11-05T14:00:00Z',
    },
    {
      title: '放松一下',
      details: '休息和放松，给自己放个假。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-11-10T15:00:00Z',
    },
    {
      title: '参加在线研讨会',
      details: '参加与行业相关的在线研讨会。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-10-22T11:00:00Z',
    },
    {
      title: '创建个人博客',
      details: '上线自己的个人博客，分享经验。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: false,
      expectedCompletionDate: '2023-12-01T12:00:00Z',
    },
    {
      title: '参加书友会',
      details: '加入书友会，讨论读书体会。',
      isCompleted: false,
      completionDate: null,
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-11-15T18:00:00Z',
    },
    {
      title: '计划科技展',
      details: '为参加即将到来的科技展做好准备。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: true,
      expectedCompletionDate: '2023-12-10T09:00:00Z',
    },
    {
      title: '参加户外活动',
      details: '制定春季户外活动的方案。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: false,
      expectedCompletionDate: '2023-11-22T09:00:00Z',
    },
    {
      title: '完成自我评估',
      details: '对自己这一年的表现进行评估。',
      isCompleted: false,
      completionDate: null,
      category: '工作',
      isDeleted: true,
      expectedCompletionDate: '2023-12-30T08:00:00Z',
    },
    {
      title: '制定练习计划',
      details: '为来年的技能提升制定详细计划。',
      isCompleted: false,
      completionDate: null,
      category: '学习',
      isDeleted: true,
      expectedCompletionDate: '2023-12-15T19:00:00Z',
    },
    {
      title: '参与兴趣小组',
      details: '加入当地的兴趣小组，寻找志同道合的伙伴。',
      isCompleted: false,
      completionDate: null,
      category: '其他',
      isDeleted: false,
      expectedCompletionDate: '2023-12-05T20:00:00Z',
    },
    {
      title: '整理书籍',
      details: '清理多余的书籍并捐赠。',
      isCompleted: false,
      completionDate: null,
      category: '生活',
      isDeleted: true,
      expectedCompletionDate: '2023-11-18T11:00:00Z',
    },
  ];
  