export const tasks = [
  {
    title: '整理文件',
    details: '整理和清理办公桌，保持整洁。',
    isCompleted: true,
    completionDate: '2025-02-11T12:00:00Z',
    category: '其他',
    isDeleted: false,
    expectedCompletionDate: '2025-02-11T10:00:00Z',
  },
  {
    title: '编写代码',
    details: '编写项目代码。',
    isCompleted: true,
    completionDate: '2025-02-11T15:00:00Z',
    category: '工作',
    isDeleted: false,
    expectedCompletionDate: '2025-02-11T15:00:00Z',
  },
  {
    title: '学习新技能',
    details: '学习一项新技能。',
    isCompleted: true,
    completionDate: '2025-02-12T12:00:00Z',
    category: '学习',
    isDeleted: false,
    expectedCompletionDate: '2025-02-12T12:00:00Z',
  },
  {
    title: '购物清单',
    details: '制定购物清单。',
    isCompleted: false,
    completionDate: null,
    category: '生活',
    isDeleted: false,
    expectedCompletionDate: '2025-02-12T18:00:00Z',
  },
  {
    title: '整理照片',
    details: '整理个人照片。',
    isCompleted: false,
    completionDate: null,
    category: '其他',
    isDeleted: false,
    expectedCompletionDate: '2025-02-13T11:00:00Z',
  },
  {
    title: '编写测试用例',
    details: '编写项目测试用例。',
    isCompleted: false,
    completionDate: null,
    category: '工作',
    isDeleted: false,
    expectedCompletionDate: '2025-02-13T13:00:00Z',
  },
  {
    title: '学习JavaScript',
    details: '深入学习JavaScript。',
    isCompleted: false,
    completionDate: null,
    category: '学习',
    isDeleted: false,
    expectedCompletionDate: '2025-02-14T12:00:00Z',
  },
  {
    title: '学习CSS',
    details: '学习CSS以提升网站设计技能。',
    isCompleted: false,
    completionDate: null,
    category: '学习',
    isDeleted: false,
    expectedCompletionDate: '2025-02-14T18:00:00Z',
  },
  {
    title: '优化网站',
    details: '优化公司网站以提高用户体验。',
    isCompleted: false,
    completionDate: null,
    category: '工作',
    isDeleted: true,
    expectedCompletionDate: '2025-02-15T10:00:00Z',
  },
  {
    title: '计划下个月预算',
    details: '制定下个月的个人预算。',
    isCompleted: false,
    completionDate: null,
    category: '生活',
    isDeleted: true,
    expectedCompletionDate: '2025-02-15T12:00:00Z',
  },
  {
    title: '回复客户邮件',
    details: '回复客户关于项目进度的询问邮件。',
    isCompleted: true,
    completionDate: '2025-02-15T14:30:00Z',
    category: '工作',
    isDeleted: false,
    expectedCompletionDate: '2025-02-15T14:30:00Z',
  },
  {
    title: '学习React',
    details: '学习React以增强前端开发能力。',
    isCompleted: false,
    completionDate: null,
    category: '学习',
    isDeleted: true,
    expectedCompletionDate: '2025-02-15T15:00:00Z',
  },
  {
    title: '健身训练',
    details: '进行一小时的健身锻炼。',
    isCompleted: true,
    completionDate: '2025-02-05T17:00:00Z',
    category: '生活',
    isDeleted: false,
    expectedCompletionDate: '2025-02-15T17:00:00Z',
  },
  {
    title: '学习ES6',
    details: '学习ES6以提高代码质量。',
    isCompleted: false,
    completionDate: null,
    category: '学习',
    isDeleted: true,
    expectedCompletionDate: '2025-02-16T10:00:00Z',
  },
];