server:
  port: 8080
  servlet:
    context-path: /todo
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testsql?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 121312QIUjiER+
mybatis-plus:
  type-aliases-package: Todo_Test.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/*.xml
#  web:
#    resources:
#      static-locations: classpath:/static/
#  mvc:
#      static-path-pattern: /static/**
#    path match:
#      matching-strategy: ant_path_matcher
mybatis:
  type-aliases-package: Todo_Test.pojo
  mapper-locations: classpath:mybatis/*.xml