/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HeadNavigation: typeof import('./src/components/head/HeadNavigation.vue')['default']
    HelpWindow: typeof import('./src/components/RightPopUpWindows/HelpWindow.vue')['default']
    NewFutures: typeof import('./src/components/RightPopUpWindows/NewFutures.vue')['default']
    PersonalInformation: typeof import('./src/components/RightPopUpWindows/PersonalInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/head/SearchBox.vue')['default']
    SettingWindow: typeof import('./src/components/RightPopUpWindows/SettingWindow.vue')['default']
    SideNavigation: typeof import('./src/components/sidebar/SideNavigation.vue')['default']
    UpperRightComponent: typeof import('./src/components/head/UpperRightComponent.vue')['default']
  }
}
